### ISSUE TITLE
"Sending fatal alert BadCertificate"

### ISSUE THREAD

**Issue by 20iahazban** [rhzx86/hacker-newsfeed#1]
![image](https://user-images.githubusercontent.com/30409619/220302796-a1142454-c07a-4458-8056-983539393693.png)

**Comment by 20iahazban** [comment]
v1.0.0-x86_64-pc-windows-msvc

**Comment by richardhozak** [comment]
I've had this issue previously, seems like it originates from rustls. Does it happen everytime, or does it work sometimes?

**Comment by 20iahazban** [comment]
it turned out the root cause is my company proxy. It works fine from normal network.

**Comment by richardhozak** [comment]
Ok, good to know. I'll close the issue. If this happens in some other way, feel free to reopen/open new one.
